[package]
name = "httpserver"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
http = {path = "../http"}

serde = {version = "1.0.117",features = ["derive"]}
serde_json = "1.0.59"
rand = "0.8.5"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
toml = "0.8.19"
